---
- name: tests
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: My-Role | Update and upgrade yum packages
      yum:
        name: "*"
        update_cache: true
        state: latest

    - name: My-Role | Install additional packages
      yum:
        name: "{{ installed_packages }}"
        state: latest
      vars:
        installed_packages:
          - nginx
